In [4]:
import numpy as np
import pandas as pd

In [5]:
data = pd.read_csv("../dataset/raw/placement_data.csv")
print(data.sample(5))
print(data.shape)
print(data.columns)
print(data.head(10))

      branch college_tier  cgpa  backlogs  coding_skills  dsa_score  \
5223     ECE       Tier-2  6.31         0            3.4        5.8
29835    CSE       Tier-1  8.18         0            7.4        5.4
21519     IT       Tier-2  7.16         0            8.8        5.2
13811    CSE       Tier-3  7.38         2            3.3        8.2
24952    CSE       Tier-3  6.12         0            4.9        5.1

       aptitude_score  communication_skills  ml_knowledge  system_design  \
5223             60.7                   3.3           7.1            3.0
29835           100.0                   6.8           5.9            4.7
21519            58.5                   7.4           3.9            0.7
13811            73.0                   5.8           4.8            4.7
24952            64.3                   4.2           4.1            3.5

       internships  projects_count  certifications  hackathons  \
5223             2               2               1           2
29835            0               4               2           0
21519            2               2               3           1
13811            1               2               2           1
24952            0               3               1           1

       open_source_contributions  extracurriculars  placement_status  \
5223                           0                 0                 0
29835                          1                 1                 1
21519                          1                 1                 0
13811                          0                 1                 1
24952                          0                 2                 0

       salary_package_lpa
5223                  NaN
29835               19.77
21519                 NaN
13811               15.54
24952                 NaN
(99999, 18)
Index(['branch', 'college_tier', 'cgpa', 'backlogs', 'coding_skills',
       'dsa_score', 'aptitude_score', 'communication_skills', 'ml_knowledge',
       'system_design', 'internships', 'projects_count', 'certifications',
       'hackathons', 'open_source_contributions', 'extracurriculars',
       'placement_status', 'salary_package_lpa'],
      dtype='str')
     branch college_tier  cgpa  backlogs  coding_skills  dsa_score  \
0       ECE       Tier-3  6.70         0            7.6        4.4
1  Chemical       Tier-2  5.70         0            5.4        7.9
2        EE       Tier-2  7.19         0            5.6        6.8
3        CE       Tier-2  6.48         0            5.2        3.1
4       CSE       Tier-2  6.71         1            5.9        4.7
5       CSE       Tier-3  6.21         1            6.7        6.5
6       CSE       Tier-3  7.91         0            7.0        3.9
7        IT       Tier-3  6.95         0            6.1        6.0
8        CE       Tier-2  7.03         0            5.1        2.5
9        EE       Tier-2  7.34         3            4.7        6.2

   aptitude_score  communication_skills  ml_knowledge  system_design  \
0            49.5                   3.7           6.4            0.3
1            72.0                   8.3           6.3            1.9
2            79.1                   7.4           4.4            5.2
3            48.4                   5.0           1.1            6.7
4            61.2                   4.3           2.7            2.8
5            69.9                   5.0           4.0            5.2
6            61.5                   6.7           4.9            2.2
7            44.4                   5.5           4.5            6.3
8            54.7                   6.4           6.2            3.2
9            78.8                   5.9           6.7            5.2

   internships  projects_count  certifications  hackathons  \
0            1               4               4           3
1            0               4               0           0
2            1               3               2           1
3            1               4               3           0
4            1               2               0           3
5            2               3               3           2
6            2               5               2           1
7            1               2               1           1
8            1               3               0           3
9            1               2               1           1

   open_source_contributions  extracurriculars  placement_status  \
0                          2                 1                 1
1                          0                 0                 0
2                          2                 0                 1
3                          0                 0                 0
4                          0                 1                 1
5                          0                 1                 1
6                          0                 3                 1
7                          1                 0                 0
8                          0                 1                 1
9                          0                 0                 1

   salary_package_lpa
0               14.75
1                 NaN
2               19.06
3                 NaN
4               13.42
5               16.47
6               16.51
7                 NaN
8               13.49
9               17.95

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   branch                     99999 non-null  str
 1   college_tier               99999 non-null  str
 2   cgpa                       99999 non-null  float64
 3   backlogs                   99999 non-null  int64
 4   coding_skills              99999 non-null  float64
 5   dsa_score                  99999 non-null  float64
 6   aptitude_score             99999 non-null  float64
 7   communication_skills       99999 non-null  float64
 8   ml_knowledge               99999 non-null  float64
 9   system_design              99999 non-null  float64
 10  internships                99999 non-null  int64
 11  projects_count             99999 non-null  int64
 12  certifications             99999 non-null  int64
 13  hackathons                 99999 non-null  int64
 14  open_source_contributions  99999 non-null  int64
 15  extracurriculars           99999 non-null  int64
 16  placement_status           99999 non-null  int64
 17  salary_package_lpa         68474 non-null  float64
dtypes: float64(8), int64(8), str(2)
memory usage: 13.7 MB

In [7]:
print("Rows and Columns:", data.shape)
print("\nColumn Names:")
print(data.columns.tolist())
print("\nDataset Info:")
data.info()

Rows and Columns: (99999, 18)

Column Names:
['branch', 'college_tier', 'cgpa', 'backlogs', 'coding_skills', 'dsa_score', 'aptitude_score', 'communication_skills', 'ml_knowledge', 'system_design', 'internships', 'projects_count', 'certifications', 'hackathons', 'open_source_contributions', 'extracurriculars', 'placement_status', 'salary_package_lpa']

Dataset Info:
<class 'pandas.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   branch                     99999 non-null  str
 1   college_tier               99999 non-null  str
 2   cgpa                       99999 non-null  float64
 3   backlogs                   99999 non-null  int64
 4   coding_skills              99999 non-null  float64
 5   dsa_score                  99999 non-null  float64
 6   aptitude_score             99999 non-null  float64
 7   communication_skills       99999 non-null  float64
 8   ml_knowledge               99999 non-null  float64
 9   system_design              99999 non-null  float64
 10  internships                99999 non-null  int64
 11  projects_count             99999 non-null  int64
 12  certifications             99999 non-null  int64
 13  hackathons                 99999 non-null  int64
 14  open_source_contributions  99999 non-null  int64
 15  extracurriculars           99999 non-null  int64
 16  placement_status           99999 non-null  int64
 17  salary_package_lpa         68474 non-null  float64
dtypes: float64(8), int64(8), str(2)
memory usage: 13.7 MB

In [8]:
data.describe()
data.nunique()

branch                          7
college_tier                    3
cgpa                          597
backlogs                        4
coding_skills                  91
dsa_score                      91
aptitude_score                765
communication_skills           91
ml_knowledge                  101
system_design                 101
internships                     4
projects_count                  6
certifications                  5
hackathons                      4
open_source_contributions       3
extracurriculars                4
placement_status                2
salary_package_lpa           1654
dtype: int64

In [9]:
missing_values = data.isnull().sum()
print("Missing values in each column:")
print(missing_values)
print("\nTotal missing values:", missing_values.sum())

Missing values in each column:
branch                           0
college_tier                     0
cgpa                             0
backlogs                         0
coding_skills                    0
dsa_score                        0
aptitude_score                   0
communication_skills             0
ml_knowledge                     0
system_design                    0
internships                      0
projects_count                   0
certifications                   0
hackathons                       0
open_source_contributions        0
extracurriculars                 0
placement_status                 0
salary_package_lpa           31525
dtype: int64

Total missing values: 31525

In [10]:
count_dublicate = data.duplicated().sum()
count_dublicate

np.int64(0)

In [11]:
data.describe()

,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status,salary_package_lpa
count,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,99999.000000,68474.000000
mean,7.206383,0.547015,5.995179,5.500713,64.990516,5.990617,4.508740,4.008216,1.095051,2.397284,1.499845,0.745827,0.450995,1.151102,0.684747,17.308048
std,0.925239,0.862729,1.496276,1.781970,11.990952,1.496559,1.968285,1.778413,0.940262,1.242835,1.114075,0.884185,0.671063,0.965167,0.464619,2.601045
min,4.000000,0.000000,1.000000,1.000000,20.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.880000
25%,6.580000,0.000000,5.000000,4.300000,56.800000,5.000000,3.200000,2.800000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,15.530000
50%,7.210000,0.000000,6.000000,5.500000,65.000000,6.000000,4.500000,4.000000,1.000000,2.000000,1.000000,0.000000,0.000000,1.000000,1.000000,17.250000
75%,7.830000,1.000000,7.000000,6.700000,73.100000,7.000000,5.900000,5.200000,2.000000,3.000000,2.000000,1.000000,1.000000,2.000000,1.000000,19.040000
max,10.000000,3.000000,10.000000,10.000000,100.000000,10.000000,10.000000,10.000000,3.000000,5.000000,4.000000,3.000000,2.000000,3.000000,1.000000,28.330000

In [12]:
print("branch:-",data["branch"].value_counts())
print("placement Status:-",data["placement_status"].value_counts())
print("Collage tier:-",data["college_tier"].value_counts())

branch:- branch
CSE         25046
IT          16065
ECE         14938
EE          12092
ME          12008
CE          10024
Chemical     9826
Name: count, dtype: int64
placement Status:- placement_status
1    68474
0    31525
Name: count, dtype: int64
Collage tier:- college_tier
Tier-3    45222
Tier-2    39910
Tier-1    14867
Name: count, dtype: int64

In [13]:
data.columns

Index(['branch', 'college_tier', 'cgpa', 'backlogs', 'coding_skills',
       'dsa_score', 'aptitude_score', 'communication_skills', 'ml_knowledge',
       'system_design', 'internships', 'projects_count', 'certifications',
       'hackathons', 'open_source_contributions', 'extracurriculars',
       'placement_status', 'salary_package_lpa'],
      dtype='str')

In [14]:
data.nunique()

branch                          7
college_tier                    3
cgpa                          597
backlogs                        4
coding_skills                  91
dsa_score                      91
aptitude_score                765
communication_skills           91
ml_knowledge                  101
system_design                 101
internships                     4
projects_count                  6
certifications                  5
hackathons                      4
open_source_contributions       3
extracurriculars                4
placement_status                2
salary_package_lpa           1654
dtype: int64

In [15]:
numbric_data = data.select_dtypes(include="number")
print("Numbric data sets:-\n")
numbric_data.agg(['max','min'])

Numbric data sets:-

,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status,salary_package_lpa
max,10.0,3,10.0,10.0,100.0,10.0,10.0,10.0,3,5,4,3,2,3,1,28.33
min,4.0,0,1.0,1.0,20.0,1.0,0.0,0.0,0,0,0,0,0,0,0,6.88

In [16]:
print(data.describe())
print(data.nunique())
print(data.value_counts())

               cgpa      backlogs  coding_skills     dsa_score  \
count  99999.000000  99999.000000   99999.000000  99999.000000
mean       7.206383      0.547015       5.995179      5.500713
std        0.925239      0.862729       1.496276      1.781970
min        4.000000      0.000000       1.000000      1.000000
25%        6.580000      0.000000       5.000000      4.300000
50%        7.210000      0.000000       6.000000      5.500000
75%        7.830000      1.000000       7.000000      6.700000
max       10.000000      3.000000      10.000000     10.000000

       aptitude_score  communication_skills  ml_knowledge  system_design  \
count    99999.000000          99999.000000  99999.000000   99999.000000
mean        64.990516              5.990617      4.508740       4.008216
std         11.990952              1.496559      1.968285       1.778413
min         20.000000              1.000000      0.000000       0.000000
25%         56.800000              5.000000      3.200000       2.800000
50%         65.000000              6.000000      4.500000       4.000000
75%         73.100000              7.000000      5.900000       5.200000
max        100.000000             10.000000     10.000000      10.000000

        internships  projects_count  certifications    hackathons  \
count  99999.000000    99999.000000    99999.000000  99999.000000
mean       1.095051        2.397284        1.499845      0.745827
std        0.940262        1.242835        1.114075      0.884185
min        0.000000        0.000000        0.000000      0.000000
25%        0.000000        1.000000        1.000000      0.000000
50%        1.000000        2.000000        1.000000      0.000000
75%        2.000000        3.000000        2.000000      1.000000
max        3.000000        5.000000        4.000000      3.000000

       open_source_contributions  extracurriculars  placement_status  \
count               99999.000000      99999.000000      99999.000000
mean                    0.450995          1.151102          0.684747
std                     0.671063          0.965167          0.464619
min                     0.000000          0.000000          0.000000
25%                     0.000000          0.000000          0.000000
50%                     0.000000          1.000000          1.000000
75%                     1.000000          2.000000          1.000000
max                     2.000000          3.000000          1.000000

       salary_package_lpa
count        68474.000000
mean            17.308048
std              2.601045
min              6.880000
25%             15.530000
50%             17.250000
75%             19.040000
max             28.330000
branch                          7
college_tier                    3
cgpa                          597
backlogs                        4
coding_skills                  91
dsa_score                      91
aptitude_score                765
communication_skills           91
ml_knowledge                  101
system_design                 101
internships                     4
projects_count                  6
certifications                  5
hackathons                      4
open_source_contributions       3
extracurriculars                4
placement_status                2
salary_package_lpa           1654
dtype: int64
branch  college_tier  cgpa  backlogs  coding_skills  dsa_score  aptitude_score  communication_skills  ml_knowledge  system_design  internships  projects_count  certifications  hackathons  open_source_contributions  extracurriculars  placement_status  salary_package_lpa
ECE     Tier-3        6.70  0         7.6            4.4        49.5            3.7                   6.4           0.3            1            4               4               3           2                          1                 1                 14.75                 1
EE      Tier-2        7.19  0         5.6            6.8        79.1            7.4                   4.4           5.2            1            3               2               1           2                          0                 1                 19.06                 1
CSE     Tier-2        6.71  1         5.9            4.7        61.2            4.3                   2.7           2.8            1            2               0               3           0                          1                 1                 13.42                 1
        Tier-3        6.21  1         6.7            6.5        69.9            5.0                   4.0           5.2            2            3               3               2           0                          1                 1                 16.47                 1
                      7.91  0         7.0            3.9        61.5            6.7                   4.9           2.2            2            5               2               1           0                          3                 1                 16.51                 1
                                                                                                                                                                                                                                                                                ..
ME      Tier-2        6.54  1         3.5            6.5        55.0            6.7                   1.4           6.6            1            4               1               0           0                          1                 1                 13.29                 1
IT      Tier-1        7.99  0         9.2            3.6        45.2            6.3                   4.0           3.9            1            2               1               1           0                          1                 1                 18.51                 1
        Tier-3        7.46  0         4.8            6.8        59.5            7.6                   5.6           2.4            1            2               3               0           1                          0                 1                 16.58                 1
EE      Tier-2        7.94  0         4.9            9.1        55.1            6.1                   3.5           5.2            0            2               1               0           1                          2                 1                 17.24                 1
ME      Tier-3        6.63  0         5.0            8.0        65.0            5.7                   6.2           0.2            1            4               2               0           0                          1                 1                 17.01                 1
Name: count, Length: 68474, dtype: int64

In [17]:
data.groupby("placement_status")["salary_package_lpa"].apply(lambda x: x.isna().sum())

placement_status
0    31525
1        0
Name: salary_package_lpa, dtype: int64

In [18]:
# Count missing values for every column
missing_counts = data.isna().sum()

# Filter to only display columns that actually have missing values
missing_counts[missing_counts > 0]

salary_package_lpa    31525
dtype: int64